#!/usr/bin/env python3
import argparse,hashlib,json,sys
from pathlib import Path
HERE=Path(__file__).resolve().parent;ROOT=HERE.parents[2];sys.path[:0]=[str(HERE.parent)]
from relation_v2.protocol import frozen_splits
from relation_v4.io import sha256
from relation_v8.run import atomic_json
def main():
 p=argparse.ArgumentParser();p.add_argument('--corpus',choices=['hatemm','hateclipseg'],required=True);p.add_argument('--split',choices=['val'],default='val');p.add_argument('--out-dir',required=True);a=p.parse_args();out=Path(a.out_dir);out.mkdir(parents=True,exist_ok=False);src=ROOT/f'results/reproduction/asr/{a.corpus}_all/timestamped_chunks.jsonl';records={r['video_id']:r for r in map(json.loads,open(src))};ids=[v for v in frozen_splits(a.corpus)[a.split] if records.get(v,{}).get('chunks')];arms=['masked_branch_reset','causal_continuous'];cfg={'method':'relation_v17_dual_context_temporal_judge_formal','status':'PREREGISTERED_BEFORE_FORWARD_OR_GT','test_informed_design_from_v16':True,'corpus':a.corpus,'split':a.split,'input':'ASR chunks only','asr_source':str(src.resolve()),'asr_source_sha256':sha256(src),'video_ids':ids,'video_ids_sha256':hashlib.sha256(''.join(v+'\n' for v in ids).encode()).hexdigest(),'n_videos':len(ids),'n_chunks':sum(len(records[v]['chunks']) for v in ids),'arms':arms,'sequential_reference_subset':[],'same_tokens_prompt_chunks_all_arms':True,'token_packing':'per-video exact LCP of full sequential prompt token IDs','roles':{'causal_continuous':'video prior = preregistered arithmetic mean of chunk scores','masked_branch_reset':'isolated-semantics locator = chunk score minus video mean, mapped to 1fps by nearest ASR chunk center; uncovered frames use nearest chunk; missing valid ASR gives zero correction'},'lambda_grid':[0,.01,.025,.05,.1,.2,.4],'paired_video_bootstrap_B':500,'shuffle_gate_B':32,'test_shuffle_B':200,'selection':'paired-video 95% CI lower bounds require pooled AP/ROC noninferior; within macro one metric strictly improves and other noninferior; improved within metric exceeds q95 of 32 deterministic within-video time shuffles; otherwise lambda0 exact fallback','gt_opened':False,'forward_implementation':str((ROOT/'scripts/reproduction_baselines/relation_v16/forward.py').resolve()),'forward_implementation_sha256':sha256(ROOT/'scripts/reproduction_baselines/relation_v16/forward.py')};atomic_json(out/'preregistered_config.json',cfg);print(json.dumps({'sha256':sha256(out/'preregistered_config.json'),'videos':len(ids),'chunks':cfg['n_chunks']},indent=2))
if __name__=='__main__':main()
