#!/usr/bin/env python3
import argparse,hashlib,json,sys
from pathlib import Path
HERE=Path(__file__).resolve().parent;ROOT=HERE.parents[2];sys.path[:0]=[str(HERE.parent),str(ROOT/'scripts/duplex'),str(ROOT/'scripts/reproduction_baselines')]
from relation_v2.protocol import frozen_splits
from relation_v8.run import atomic_json
from relation_v4.io import sha256
ARMS=['masked_branch_reset','masked_continuous','causal_branch_reset','causal_continuous']
def main():
 p=argparse.ArgumentParser();p.add_argument('--corpus',choices=['hatemm','hateclipseg'],required=True);p.add_argument('--out-dir',required=True);p.add_argument('--hcs-limit',type=int,default=24);a=p.parse_args();out=Path(a.out_dir);out.mkdir(parents=True,exist_ok=False);src=ROOT/f'results/reproduction/asr/{a.corpus}_all/timestamped_chunks.jsonl';records={r['video_id']:r for r in map(json.loads,open(src))};ids=[v for v in frozen_splits(a.corpus)['test'] if records.get(v,{}).get('chunks')]
 if a.corpus=='hateclipseg' and a.hcs_limit:ids=sorted(ids,key=lambda v:hashlib.sha256(('v16-hcs:'+v).encode()).hexdigest())[:a.hcs_limit]
 subset=sorted(ids,key=lambda v:(-len(records[v]['chunks']),v))[:12];cfg={'method':'relation_v16_asr_attention_position_2x2','status':'PREREGISTERED_BEFORE_FORWARD_OR_GT','corpus':a.corpus,'split':'test','test_informed':True,'input':'ASR chunk text only','asr_source':str(src.resolve()),'asr_source_sha256':sha256(src),'video_ids':ids,'video_ids_sha256':hashlib.sha256(''.join(v+'\n' for v in ids).encode()).hexdigest(),'n_videos':len(ids),'n_chunks':sum(len(records[v]['chunks']) for v in ids),'arms':ARMS,'position_attention_factorial':{'attention':['masked branch isolation','full causal'],'position':['branch reset','continuous']},'token_packing':'per-video exact longest-common-prefix of complete sequential prompt token IDs; every prefix+branch asserted identical to its sequential prompt','sequential_reference_subset':subset,'sequential_subset_rule':'12 selected videos with most ASR chunks; video-id tie break','same_tokens_prompt_chunks_all_arms':True,'raw_outputs_before_gt':['per_chunk_raw.jsonl','raw_manifest.json'],'evaluation_after_raw_freeze':['chunk pooled AUC','within-video macro AUC','cross-video span-vs-negative-video AUC','video bootstrap 95% CI'],'bootstrap_videos':2000,'prompt_implementation':str((ROOT/'scripts/duplex/masked_parallel_isolation_pilot.py').resolve()),'prompt_implementation_sha256':sha256(ROOT/'scripts/duplex/masked_parallel_isolation_pilot.py'),'forward_implementation_sha256':sha256(ROOT/'scripts/reproduction_baselines/relation_v16/forward.py'),'gt_opened':False};atomic_json(out/'preregistered_config.json',cfg);print(json.dumps({'config':str((out/'preregistered_config.json').resolve()),'sha256':sha256(out/'preregistered_config.json'),'n_videos':len(ids),'n_chunks':cfg['n_chunks']},indent=2))
if __name__=='__main__':main()
